name: Codeclimate Coverage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build libraries
        run: yarn build
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
            coverageCommand: yarn coverage
            coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov

